version: '3.8'

services:
  can_analyze_our_agent:
    build: .
    container_name: can_analyze_our_agent
    ports:
      - "8000:8000"
    environment:
      - MODE=production
      - LOG_LEVEL=INFO
    volumes:
      - ./config.json:/app/config.json:ro
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - agent_network

networks:
  agent_network:
    driver: bridge
